// WARNING: This file has automatically been generated on Thu, 03 Jan 2019 19:45:13 CST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

#include "c_api/AutoTune_c.h"
#include "c_api/AuxIndexStructures_c.h"
#include "c_api/Clustering_c.h"
#include "c_api/Index_c.h"
#include "c_api/IndexFlat_c.h"
#include "c_api/IndexIVF_c.h"
#include "c_api/IndexLSH_c.h"
#include "c_api/MetaIndexes_c.h"
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

