// WARNING: This file has automatically been generated on Thu, 03 Jan 2019 19:45:13 CST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

/*
Package emd provides Go bindings for emd
*/
package faiss_go
