// WARNING: This file has automatically been generated on Sat, 19 Jan 2019 12:42:42 CST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

/*
Package emd provides Go bindings for emd
*/
package faiss_go
