// WARNING: This file has automatically been generated on Fri, 04 Jan 2019 16:12:37 CST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package faiss_go

/*
#cgo darwin LDFLAGS: -Lc_api -lfaiss_c
#cgo darwin LDFLAGS: -L.. -lfaiss
#cgo linux LDFLAGS: -Lc_api -lfaiss_c
#cgo linux LDFLAGS: -L.. -lfaiss
#cgo darwin LDFLAGS: -Wl,-undefined,dynamic_lookup
#cgo darwin LDFLAGS: -lblas -llapack
#cgo linux LDFLAGS: -L/usr/local/lib -lstdc++ -pthread -lcrypt -lm -fopenmp -lblas -llapack
#include "c_api/AutoTune_c.h"
#include "c_api/AuxIndexStructures_c.h"
#include "c_api/Clustering_c.h"
#include "c_api/Index_c.h"
#include "c_api/IndexFlat_c.h"
#include "c_api/IndexIVF_c.h"
#include "c_api/IndexLSH_c.h"
#include "c_api/MetaIndexes_c.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

// Faissparameterrange as declared in c_api/AutoTune_c.h:28
type Faissparameterrange C.FaissParameterRange

// Faissparameterspace as declared in c_api/AutoTune_c.h:38
type Faissparameterspace C.FaissParameterSpace

// Faissrangesearchresult as declared in c_api/Index_c.h:23
type Faissrangesearchresult C.FaissRangeSearchResult

// Faissidselector as declared in c_api/Index_c.h:26
type Faissidselector C.FaissIDSelector

// Faissindex as declared in c_api/Index_c.h:35
type Faissindex C.FaissIndex

// Faissidselectorrange as declared in c_api/AuxIndexStructures_c.h:56
type Faissidselectorrange C.FaissIDSelectorRange

// Faissidselectorbatch as declared in c_api/AuxIndexStructures_c.h:70
type Faissidselectorbatch C.FaissIDSelectorBatch

// Faissbufferlist as declared in c_api/AuxIndexStructures_c.h:81
type Faissbufferlist C.FaissBufferList

// Faissbuffer as declared in c_api/AuxIndexStructures_c.h:90
type Faissbuffer struct {
	Ids            []int
	Dis            []float32
	refe3f43253    *C.FaissBuffer
	allocse3f43253 interface{}
}

// Faissrangesearchpartialresult as declared in c_api/AuxIndexStructures_c.h:104
type Faissrangesearchpartialresult C.FaissRangeSearchPartialResult

// Faissqueryresult as declared in c_api/AuxIndexStructures_c.h:123
type Faissqueryresult C.FaissQueryResult

// Faissclusteringparameters as declared in c_api/Clustering_c.h:38
type Faissclusteringparameters struct {
	Niter                int32
	Nredo                int32
	Verbose              int32
	Spherical            int32
	UpdateIndex          int32
	FrozenCentroids      int32
	MinPointsPerCentroid int32
	MaxPointsPerCentroid int32
	Seed                 int32
	ref9c9731c3          *C.FaissClusteringParameters
	allocs9c9731c3       interface{}
}

// Faissclustering as declared in c_api/Clustering_c.h:59
type Faissclustering C.FaissClustering

// Faissindexflat as declared in c_api/IndexFlat_c.h:26
type Faissindexflat C.FaissIndexFlat

// Faissindexflatip as declared in c_api/IndexFlat_c.h:69
type Faissindexflatip C.FaissIndexFlatIP

// Faissindexflatl2 as declared in c_api/IndexFlat_c.h:76
type Faissindexflatl2 C.FaissIndexFlatL2

// Faissindexflatl2baseshift as declared in c_api/IndexFlat_c.h:86
type Faissindexflatl2baseshift C.FaissIndexFlatL2BaseShift

// Faissindexrefineflat as declared in c_api/IndexFlat_c.h:95
type Faissindexrefineflat C.FaissIndexRefineFlat

// Faissindexflat1d as declared in c_api/IndexFlat_c.h:105
type Faissindexflat1d C.FaissIndexFlat1D

// Faissindexivf as declared in c_api/IndexIVF_c.h:40
type Faissindexivf C.FaissIndexIVF

// Faissindexivfstats as declared in c_api/IndexIVF_c.h:120
type Faissindexivfstats struct {
	Nq             uint
	Nlist          uint
	Ndis           uint
	refda0d0668    *C.FaissIndexIVFStats
	allocsda0d0668 interface{}
}

// Faissindexivfflat as declared in c_api/IndexIVF_c.h:132
type Faissindexivfflat C.FaissIndexIVFFlat

// Faissindexlsh as declared in c_api/IndexLSH_c.h:24
type Faissindexlsh C.FaissIndexLSH

// Faissindexidmap as declared in c_api/MetaIndexes_c.h:23
type Faissindexidmap C.FaissIndexIDMap

// Faissindexidmap2 as declared in c_api/MetaIndexes_c.h:40
type Faissindexidmap2 C.FaissIndexIDMap2

// Faissindexshards as declared in c_api/MetaIndexes_c.h:49
type Faissindexshards C.FaissIndexShards
